#!/bin/bash
# Delete all local branches that have been merged, u know, clean up :D
# just in case skip the one you are on, master/main and dev
# I never remember this, so maded as scipt
# shellcheck disable=SC2312
git branch --merged | grep -E -v "(^\*|master|main|dev)" | xargs git branch -d
