#!/bin/bash
# Delete all local branches that have been merged, u know, clean up :D
# just in case skip the one you are on, master/main and dev
# I never remember this, so maded as scipt
git branch --merged | egrep -v "(^\*|master|main|dev)" | xargs git branch -d