#!/bin/bash
# Helper to quickly search last pass passwords
# ONLY WORKS ON MAC
# features:
# * fuzzy search
# * pushes pw to clipboard
# * waits for any key to clear clipboard

if ! command -v lpass &> /dev/null; then
    echo "Need to have lpass installed. Do: brew install lastpass-cli"
    exit 1
fi

if ! command -v fzf &> /dev/null; then
    echo "Need to have fzf installed. Do: brew install fzf"
    exit 1
fi

if ! lpass status -q; then
    if [ -z ${EMAIL+x} ]; then
        echo "No EMAIL variable available, bailing"
        exit 1
    fi
    lpass login $EMAIL
fi

lpass ls --long | fzf | sed -E "s/.*\[id:[[:space:]]([0-9]+)\].*/\1/" | xargs -I {} lpass show --password {} | pbcopy

read -n 1 -s -r -p "Press any key when done..."

pbcopy </dev/null

echo " Clipboard cleared ʕっ•ᴥ•ʔっ"