name: Checks
on: [push]
jobs:
  checks:
    # not running checks on mac, not needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ShellCheck
        run: sudo apt install shellcheck
      - name: ShellCheck
        run: shellcheck -x -o all scripts/* nipsulidotfiles.sh install_mac